[client]
toolbarMode = "minimal"                    # Режим тулбара: "auto", "minimal", "development"

[server]
headless = true
port = 8501
address = "0.0.0.0"
runOnSave = true
allowRunOnSave = true

[browser]
serverAddress = "127.0.0.1"
serverPort = 8501